### PR TITLE
Milestone 2: User interface

### PR DESCRIPTION
**Pull request by patrikis-angelos**
### Milestone 2: User interface
In this milestone we:
- Added the basic user interface by displaying console output and waiting for user input.

### CODE REVIEW

**Review by mahmoud717 — CHANGES_REQUESTED** [review]
### Changes required ♻️ 

**Hello @patrick-angelos  & @AymenBida**

Great job with the project so far it looks amazing, but there are still some changes to be made:
 
---

- [x] please make sure to fix all of your linters problems before doing any of what follows.

### Requested 🔴 

- [x] First of all, your main.rb file should be executable. It might be so on your pc, but you need to push the permissions to github by using the following command
`git update-index --chmod=+x ./bin/main.rb`.

- [x] secondly, You did a good job mocking the game, but there are still some changes to be made:
- the game informs player if the selected move is invalid (without computing what an invalid move is)
- game displays board after the player move (without computing which spots on the board are taken)
- game informs player if the selected move is a winning move (without computing the winning move)
- game informs player if the selected move is a draw move (without computing draw)


---

please make these changes and request another code review.

if you have any questions don't hesitate to contact me on slack **MahmoudMohammad**

**Comment by descholar-ceo** [comment]
# This Pull Request is under review by [descholar-ceo](https://github.com/descholar-ceo) :eyes: :eyes: 
## Please wait a bit ...

**Review by descholar-ceo — CHANGES_REQUESTED** [review]
# Status: Changes Required :vertical_traffic_light: :warning: 
## Hello @patrick-angelos and @AymenBida  :handshake: :handshake: :handshake: 

:+1: This is good to make it this far, your project is really nice, congratulations on the good work you have done so far.
:+1: I liked that you have tried to implemented the requested changes from the previous review, keep it up, and your project is really almost done.
#### :warning: However we need to make few changes to mark this project approved, don't feel discouraged because of being asked some changes more and more, that's beacuse this is a learning process, and we are here to help you to become an out-standing developer. See the requested change below :point_down: :point_down: :point_down: 
### Note: All of requested changes which are marked as [Required] are mandatory to be implemented in order to get this project approved, others which are marked as [Optional] are nice to have in your project to make it outstanding

# [Required Changes] :red_circle: 
- [ ] While you are mocking the game's flow, make sure that the app doesn't crash, when I clicked `y` for reading instructions, the app crashed, and when I clicked `Enter` to continue the app crashed as well, looking at your codes, it seems that you implemented almost all requirements, but you still need to make the app keeps running, fix that before submitting for the re-review. Below is the error message I got after the game has crashed:
```ruby
Traceback (most recent call last):
        2: from bin/main.rb:11:in `<main>'
        1: from bin/main.rb:11:in `loop'
bin/main.rb:13:in `block in <main>': undefined local variable or method `board' for main:Object (NameError)
```
___
_If anything seems to be unclear to you, reachout and ask anything by commenting on this Pull Request and mention me as [descholar-ceo](https://github.com/descholar-ceo), I will receive a notification and will respond._

[GitHub](https://github.com/descholar-ceo) | [LinkedIn](https://linkedin.com/in/mugirase-emmanuel) | [Twitter](https://twitter.com/descholar3)

_Reviewed by [Mugirase Emmanuel (descholar)](https://github.com/descholar-ceo)_

**Review by mahmoud717 — CHANGES_REQUESTED** [review]
### Changes required ♻️ 

**Hello @patrick-angelos  & @AymenBida**

Great job with the project so far it looks amazing, but there are still some changes to be made:
 
---
### Requested 🔴 

- [ ] the game must display an actual board when it starts and on every turn.

- [ ] the only parts that are not required for this milestone is the win/draw calculation. So you must make your game look like the final product except for the last part.

---

please make these changes and request another code review.

if you have any questions don't hesitate to contact me on slack **MahmoudMohammad**

**Review by mahmoud717 — APPROVED** [review]
### STATUS: APPROVED ✔️ ✔️ 

**hi @patrick-angelos  & @AymenBida**

**Great job with making all of the requirements. the project is approved, you can go ahead and merge this pull request**

**Pull request merged**
